// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iWaiTLt8mAup4ReehswsSx
// Component: UvuH9QiGqNGm

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import Link1 from "../../Link1"; // plasmic-import: Wk3pm7NzsIY9/component
import Link2 from "../../Link2"; // plasmic-import: f0ftlBRhAHPN/component
import Link3 from "../../Link3"; // plasmic-import: P6OuWwiFq4gQ/component
import Link4 from "../../Link4"; // plasmic-import: b5zzKfYNksQk/component
import Link5 from "../../Link5"; // plasmic-import: jy_zqM-l3sYE/component
import Link6 from "../../Link6"; // plasmic-import: qdfwHKfwtv8_/component
import Button from "../../Button"; // plasmic-import: f3lmI1Q2JQuQ/component
import FooterMain from "../../FooterMain"; // plasmic-import: qoZVCK7paFuV/component
import { PlasmicHead } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantssppb0UOhrN5L } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: Sppb0uOhrN5l/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: iWaiTLt8mAup4ReehswsSx/projectcss
import sty from "./Plasmic_7KelebihanDanKegunaanMotorListrik.module.css"; // plasmic-import: UvuH9QiGqNGm/css

import ProfileCircleSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__ProfileCircleSvgrepoCom1Svg"; // plasmic-import: 0qa3aoynIlk5/icon
import BestSellersvgIcon from "./icons/PlasmicIcon__BestSellersvg"; // plasmic-import: gEr3vmMDIr_A/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: q0SxIWf05NzX/icon
import MotorcyclesvgIcon from "./icons/PlasmicIcon__Motorcyclesvg"; // plasmic-import: bB21gLC1MPi2/icon
import PinsvgIcon from "./icons/PlasmicIcon__Pinsvg"; // plasmic-import: d5Rc8pnBZxlJ/icon
import ArrowLeftSvgrepoComsvgIcon from "./icons/PlasmicIcon__ArrowLeftSvgrepoComsvg"; // plasmic-import: n23QXdz0xMhj/icon

createPlasmicElementProxy;

export type Plasmic_7KelebihanDanKegunaanMotorListrik__VariantMembers = {};
export type Plasmic_7KelebihanDanKegunaanMotorListrik__VariantsArgs = {};
type VariantPropType =
  keyof Plasmic_7KelebihanDanKegunaanMotorListrik__VariantsArgs;
export const Plasmic_7KelebihanDanKegunaanMotorListrik__VariantProps =
  new Array<VariantPropType>();

export type Plasmic_7KelebihanDanKegunaanMotorListrik__ArgsType = {};
type ArgPropType = keyof Plasmic_7KelebihanDanKegunaanMotorListrik__ArgsType;
export const Plasmic_7KelebihanDanKegunaanMotorListrik__ArgProps =
  new Array<ArgPropType>();

export type Plasmic_7KelebihanDanKegunaanMotorListrik__OverridesType = {
  root?: Flex__<"div">;
  navigationBar?: Flex__<typeof NavigationBar>;
  link1?: Flex__<typeof Link1>;
  link2?: Flex__<typeof Link2>;
  link3?: Flex__<typeof Link3>;
  link4?: Flex__<typeof Link4>;
  link5?: Flex__<typeof Link5>;
  link6?: Flex__<typeof Link6>;
  images03?: Flex__<typeof PlasmicImg__>;
  footerMain?: Flex__<typeof FooterMain>;
  pageMetadataOverride?: Flex__<typeof PlasmicHead>;
};

export interface Default_7KelebihanDanKegunaanMotorListrikProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function Plasmic_7KelebihanDanKegunaanMotorListrik__RenderFunc(props: {
  variants: Plasmic_7KelebihanDanKegunaanMotorListrik__VariantsArgs;
  args: Plasmic_7KelebihanDanKegunaanMotorListrik__ArgsType;
  overrides: Plasmic_7KelebihanDanKegunaanMotorListrik__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantssppb0UOhrN5L()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {Plasmic_7KelebihanDanKegunaanMotorListrik.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={Plasmic_7KelebihanDanKegunaanMotorListrik.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={Plasmic_7KelebihanDanKegunaanMotorListrik.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={
            Plasmic_7KelebihanDanKegunaanMotorListrik.pageMetadata.description
          }
        />
        <meta
          key="og:description"
          property="og:description"
          content={
            Plasmic_7KelebihanDanKegunaanMotorListrik.pageMetadata.description
          }
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={
            Plasmic_7KelebihanDanKegunaanMotorListrik.pageMetadata.description
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <section className={classNames(projectcss.all, sty.section__xYHyV)}>
            <NavigationBar
              data-plasmic-name={"navigationBar"}
              data-plasmic-override={overrides.navigationBar}
              brand={
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__aecFd
                  )}
                  component={Link}
                  href={`/`}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__bv6Xn)}
                    displayHeight={"100px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: "/plasmic/uwinfly/images/logopng.png",
                      fullWidth: 512,
                      fullHeight: 512,
                      aspectRatio: undefined
                    }}
                  />
                </PlasmicLink__>
              }
              className={classNames("__wab_instance", sty.navigationBar)}
              closeButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__fTdQm)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "20px"
                      : "auto"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "20px"
                      : "auto"
                  }
                  src={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? {
                          src: "/plasmic/uwinfly/images/_3F1C0155019E22Ca2146D6372Fa054D8Svg.svg",
                          fullWidth: 150,
                          fullHeight: 150,
                          aspectRatio: 1
                        }
                      : "https://static1.plasmic.app/close.svg"
                  }
                />
              }
              forceOpenMenu={
                hasVariant(globalVariants, "screen", "mobile") ? false : true
              }
              itemsGap={hasVariant(globalVariants, "screen", "mobile") ? 8 : 8}
              menuItems={
                <React.Fragment>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__ygUvu
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    <Link1
                      data-plasmic-name={"link1"}
                      data-plasmic-override={overrides.link1}
                      className={classNames("__wab_instance", sty.link1)}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__zt88H
                    )}
                    component={Link}
                    href={`/about-us`}
                    platform={"nextjs"}
                  >
                    <Link2
                      data-plasmic-name={"link2"}
                      data-plasmic-override={overrides.link2}
                      className={classNames("__wab_instance", sty.link2)}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link___8QcGg
                    )}
                    component={Link}
                    href={`/Mitra`}
                    platform={"nextjs"}
                  >
                    <Link3
                      data-plasmic-name={"link3"}
                      data-plasmic-override={overrides.link3}
                      className={classNames("__wab_instance", sty.link3)}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link___2Ln
                    )}
                    component={Link}
                    href={`/Blog`}
                    platform={"nextjs"}
                  >
                    <Link4
                      data-plasmic-name={"link4"}
                      data-plasmic-override={overrides.link4}
                      className={classNames("__wab_instance", sty.link4)}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__mOYr
                    )}
                    component={Link}
                    href={`/persyaratan`}
                    platform={"nextjs"}
                  >
                    <Link5
                      data-plasmic-name={"link5"}
                      data-plasmic-override={overrides.link5}
                      className={classNames("__wab_instance", sty.link5)}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__yrKyf
                    )}
                    component={Link}
                    href={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? `/Kontak-kami`
                        : `/Kontak-kami`
                    }
                    platform={"nextjs"}
                  >
                    <Link6
                      data-plasmic-name={"link6"}
                      data-plasmic-override={overrides.link6}
                      className={classNames("__wab_instance", sty.link6)}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__idF1X
                    )}
                    component={Link}
                    href={`/Profile`}
                    platform={"nextjs"}
                  >
                    <ProfileCircleSvgrepoCom1SvgIcon
                      className={classNames(projectcss.all, sty.svg___1GJc4)}
                      role={"img"}
                    />
                  </PlasmicLink__>
                </React.Fragment>
              }
              openButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__eaTwt)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "25px"
                      : "35px"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  src={{
                    src: "/plasmic/uwinfly/images/iconsvg.svg",
                    fullWidth: 231,
                    fullHeight: 150,
                    aspectRatio: 1.537966
                  }}
                />
              }
              responsiveBreakpoint={768}
            />

            <section className={classNames(projectcss.all, sty.section__dcw8D)}>
              <div className={classNames(projectcss.all, sty.columns__jaUv5)}>
                <div
                  className={classNames(projectcss.all, sty.column__nbPhS)}
                />

                <div
                  className={classNames(projectcss.all, sty.column__s4Tc0)}
                />
              </div>
            </section>
          </section>
          <section className={classNames(projectcss.all, sty.section__kziFn)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__qnzs3)}
            >
              <div className={classNames(projectcss.all, sty.column___8CaL0)}>
                <Button
                  className={classNames("__wab_instance", sty.button__gwNAf)}
                  showStartIcon={true}
                  startIcon={
                    <BestSellersvgIcon
                      className={classNames(projectcss.all, sty.svg__gy2Zn)}
                      role={"img"}
                    />
                  }
                >
                  {"Best seller"}
                </Button>
              </div>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.column__tsPea
                )}
                component={Link}
                href={`/Produk`}
                platform={"nextjs"}
              >
                <Button
                  className={classNames("__wab_instance", sty.button__mId3M)}
                  showStartIcon={true}
                  startIcon={
                    <MotorcyclesvgIcon
                      className={classNames(projectcss.all, sty.svg__ieUtx)}
                      role={"img"}
                    />
                  }
                >
                  {"Produk"}
                </Button>
              </PlasmicLink__>
              <div className={classNames(projectcss.all, sty.column__poo08)}>
                <Button
                  className={classNames("__wab_instance", sty.button__v43UJ)}
                  link={`/Service`}
                  showStartIcon={true}
                  startIcon={
                    <PinsvgIcon
                      className={classNames(projectcss.all, sty.svg__iwot7)}
                      role={"img"}
                    />
                  }
                >
                  {"Service"}
                </Button>
              </div>
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section___2CHHi)}>
            <div className={classNames(projectcss.all, sty.columns__hy7Ey)}>
              <div className={classNames(projectcss.all, sty.column___7Y91Z)}>
                <Button
                  className={classNames("__wab_instance", sty.button___7SlR)}
                  showStartIcon={true}
                >
                  {"Best seller"}
                </Button>
              </div>
              <div className={classNames(projectcss.all, sty.column__yibTl)}>
                <Button
                  className={classNames("__wab_instance", sty.button__o6KZd)}
                  showStartIcon={true}
                  startIcon={
                    <BestSellersvgIcon
                      className={classNames(projectcss.all, sty.svg__xRuEh)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ygWc6
                    )}
                  >
                    {"Best seller"}
                  </div>
                </Button>
              </div>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.column__tdLs
                )}
                component={Link}
                href={`/Produk`}
                platform={"nextjs"}
              >
                <Button
                  className={classNames("__wab_instance", sty.button__xSdD)}
                  showStartIcon={true}
                  startIcon={
                    <MotorcyclesvgIcon
                      className={classNames(projectcss.all, sty.svg__pe6B)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vFiBo
                    )}
                  >
                    {"Produk"}
                  </div>
                </Button>
              </PlasmicLink__>
              <div className={classNames(projectcss.all, sty.column__oomDw)}>
                <Button
                  className={classNames("__wab_instance", sty.button__hnxHp)}
                  link={`/Service`}
                  showStartIcon={true}
                  startIcon={
                    <PinsvgIcon
                      className={classNames(projectcss.all, sty.svg___6E5I6)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3WTi
                    )}
                  >
                    {"Service"}
                  </div>
                </Button>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__tMai)}>
            <div className={classNames(projectcss.all, sty.columns__b4IdS)}>
              <div className={classNames(projectcss.all, sty.column__dJ4Ik)}>
                <section
                  className={classNames(projectcss.all, sty.section__duPu)}
                >
                  <div
                    className={classNames(projectcss.all, sty.columns__kD7F)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___1IrdQ)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__f8Ak6
                        )}
                        component={Link}
                        href={`/Blog`}
                        platform={"nextjs"}
                      >
                        <ArrowLeftSvgrepoComsvgIcon
                          className={classNames(projectcss.all, sty.svg__cK0Hl)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__voRjj)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ezuXb
                        )}
                      >
                        {"Januari 24, 2024"}
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4T9Jt
                    )}
                  >
                    {"7 Kelebihan dan Kegunaan Motor Listrik"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__euZ03
                    )}
                  >
                    {
                      "Kendaraan listrik saat ini tengah dikembangkan oleh produsen otomotif. "
                    }
                  </div>
                </section>
                <section
                  className={classNames(projectcss.all, sty.section___9OHv1)}
                >
                  <PlasmicImg__
                    data-plasmic-name={"images03"}
                    data-plasmic-override={overrides.images03}
                    alt={"7 Kelebihan dan Kegunaan Motor Listrik"}
                    className={classNames(sty.images03)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/uwinfly/images/newProject2Png.png",
                      fullWidth: 800,
                      fullHeight: 600,
                      aspectRatio: undefined
                    }}
                  />
                </section>
                <section
                  className={classNames(projectcss.all, sty.section__nPmYn)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qU5Gu
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile") ? (
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"Uwinfly.co.id"}
                        </span>
                        <React.Fragment>
                          {
                            " - Kendaraan listrik saat ini tengah dikembangkan oleh produsen otomotif. Bukan tanpa alasan, pasalnya banyak kegunaan motor listrik dalam kehidupan sehari-hari. \n\nMisalnya saja, motor listrik bisa berguna untuk membuat hidup lebih sehat, ramah lingkungan, hingga mengurangi polusi udara. Dengan berbagai keunggulan ini, motor listrik bisa menjadi solusi kendaraan masa depan. \n\nBagi Anda yang masih awam mungkin akan bertanya-tanya, apa itu motor listrik dan cara kerjanya? Kami akan memberikan informasi mendalam mengenai motor listrik tersebut hingga keunggulannya.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {
                            "Kegunaan Motor Listrik dalam Kehidupan Sehari-hari "
                          }
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nMotor listrik adalah sebuah kendaraan bermotor yang memakai tenaga listrik sebagai energinya. Pada motor listrik menggunakan mesin penggerak semacam dinamo. \n\nSecara umum, ada tiga komponen motor listrik yang sangat penting, yakni baterai sebagai sumber energi, dinamo atau rotor sebagai penggerak, dan V-Belt sebagai penghubung putaran rotor ke roda belakang. \n\nCara kerja motor listrik yakni arus listrik berjalan menuju dinamo dan akan menggerakkan dinamo. Perputaran dinamo ini akan diteruskan ke roda belakang melalui V-Belt. Sehingga motor listrik bisa bergerak dan berjalan sesuai dengan kencang. \n\nLantas apa fungsi motor listrik dalam kehidupan sehari hari? Kegunaan dari sepeda motor listrik yaitu sebagai kendaraan ramah lingkungan. Kendaraan yang satu ini dapat digunakan untuk mempermudah aktivitas. \n\nMisalnya untuk melakukan perjalanan jauh, mengangkut barang, hingga untuk nongkrong dengan teman-teman. Hal yang paling membanggakan yakni semua aktivitas dengan motor tersebut tidak menghasilkan polusi udara. Sehingga kualitas udara bisa tetap terjaga dan tubuh bisa tetap sehat.  \n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"Kontrol sepenuhnya motor listrik melalui ponsel"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nKini motor listrik semakin canggih dengan menyematkan teknologi IoT (Internet of Things) dan terhububung dengan ponsel. Dengan berbagai fitur mutakhir, aplikasi dirancang untuk meningkatkan pengalaman berkendara dan membantu mendapatkan manfaat maksimal dari kendaraan listrik. Salah satu fitur utama aplikasi adalah kemampuan untuk menghidupkan dan mematikan sepeda motor EV (Electric Vehicle) dari jarak jauh, langsung melalui ponsel pribadi pengendara. Hal ini memungkinkan Anda dengan cepat dan mudah menghidupkan kendaraan dan pergi ke jalan, tanpa perlu kunci atau kontak fisik dengan sakelar.\n\nSelain kemampuan start dan stop jarak jauh, aplikasi juga memungkinkan untuk melacak riwayat perjalanan, termasuk jarak yang ditempuh dan waktu yang dihabiskan setelah berkendara. Fitur ini sangat berguna untuk mengawasi kebiasaan berkendara Anda dan memantau kemajuan dari waktu ke waktu.\n\nKini motor listrik semakin canggih dengan menyematkan teknologi IoT (Internet of Things) dan terhububung dengan ponsel. Dengan berbagai fitur mutakhir, aplikasi dirancang untuk meningkatkan pengalaman berkendara dan membantu mendapatkan manfaat maksimal dari kendaraan listrik. Salah satu fitur utama aplikasi adalah kemampuan untuk menghidupkan dan mematikan sepeda motor EV (Electric Vehicle) dari jarak jauh, langsung melalui ponsel pribadi pengendara. Hal ini memungkinkan Anda dengan cepat dan mudah menghidupkan kendaraan dan pergi ke jalan, tanpa perlu kunci atau kontak fisik dengan sakelar.\n\nSelain kemampuan start dan stop jarak jauh, aplikasi juga memungkinkan untuk melacak riwayat perjalanan, termasuk jarak yang ditempuh dan waktu yang dihabiskan setelah berkendara. Fitur ini sangat berguna untuk mengawasi kebiasaan berkendara Anda dan memantau kemajuan dari waktu ke waktu\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {
                            "Kelebihan Motor Listrik Dibandingkan dengan Motor Bensin "
                          }
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"1. Ramah Lingkungan"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nPasti banyak yang penasaran, apakah motor listrik mengeluarkan asap? Nah motor listrik tidak menghasilkan asap sama sekali. Ini artinya, kendaraan tersebut tidak menghasilkan emisi gas buang yang menyebabkan polusi udara.\n\nMengutip dari laman Kemenperin.go.id, pemerintah juga telah menargetkan untuk mencapai net zero emisi di tahun 2060 mendatang. Salah satu jalan yang dilakukan oleh Pemerintah Indonesia yakni dengan memperbanyak produksi kendaraan listrik. Kemudian mewajibkan pemerintah pusat dan daerah memakai kendaraan listrik.\n\nKetika semua lapisan masyarakat telah memakai kendaraan listrik, maka akan tercipta lingkungan yang sehat. Polusi udara menjadi berkurang dan tentunya kondisi lingkungan juga bisa menjadi lebih baik lagi.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"2. Menghemat Energi Fosil"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nBahan bakar minyak merupakan sumber energi penggerak mesin kendaraan bermotor. Sayangnya BBM ini merupakan energi fosil yang tidak bisa diciptakan lagi. Keberadaanya pun bisa habis jika manusia tidak bijak memanfaatkannya. \n\nMotor listrik hadir untuk menjawab tantangan kelangkaan energi minyak. Dengan adanya kendaraan listrik, maka bisa lebih menghemat penggunaan BBM. Karena motor bertenaga listrik tidak memerlukan BBM lagi.\n\nTerlebih lagi, harga BBM saat ini cukup mahal ketimbang harga listrik. Saat Anda memakai motor listrik, maka Anda bisa hemat uang dan membantu menghemat energi BBM.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"3. Lebih Hemat Biaya Perawatan"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nSetiap kendaraan bermotor tentunya perlu perawatan harian atau bulanan. Hal ini sangat berguna agar kondisi motor tetap prima dan bisa digunakan untuk berkendara dengan lancar.\n\nPerawatan dan operasional tersebut meliputi bahan bakar, reparasi rem, pengecekan mesin, dan lain sebagainya. Untungnya saat Anda memakai kendaraan listrik, Anda akan jauh lebih hemat dari biaya-biaya tersebut. \n\nKarena motor listrik hanya perlu perawatan bagian baterai dan kondisi mesin. Hal ini akan membuat Anda lebih hemat dalam perawatan kendaraan listrik yang dimiliki.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"4. Lebih Ringan"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nMungkin Anda pernah bertanya-tanya, apakah motor listrik lebih enteng? Ternyata motor listrik memang jauh lebih ringan ketimbang motor konvensional. Hal ini karena motor listrik memakai kerangka dan mesin yang tidak terlalu berat. \n\nBagian kerangka motor listrik didesain untuk menyesuaikan berat penggunanya. Kemudian untuk mesin memakai dinamo yang tentunya lebih ringan ketimbang mesin motor biasa. Karena beratnya cukup ringan, tentunya bisa memberikan keuntungan tersendiri. \n\nMotor listrik yang ringan ini akan membuat kecepatannya jadi lebih tinggi. Anda bisa memacu kendaraan tersebut dan berakselerasi dengan lebih leluasa. Dengan catatan, kondisi medan yang Anda tempuh tidak naik turun perbukitan.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"5. Tidak Bising"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nKeunggulan motor listrik ketimbang motor konvensional yakni tidak bising. Motor listrik biasanya memiliki suara bising karena perlu pembakaran di mesin. Kemudian hasil pembakaran yang berupa gas akan dibuang melalui knalpot. \n\nHal inilah yang membuat motor konvensional memiliki bunyi yang amat bising. Sementara pada motor listrik, sama sekali tidak ada pembakaran di bagian mesin. Bunyi pada mesin motor listrik bersumber dari putaran dinamo atau rotor. \n\nSehingga motor listrik tidak akan mengeluarkan bunyi bising sama sekali. Hal tersebut akan memberikan kenyamanan berkendara untuk Anda sendiri dan lingkungan di sekitar Anda. Kehidupan bermasyarakat pun jadi lebih rukun serta lebih indah.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"6. Pengisian Daya Lebih Cepat"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nKendaraan dengan energi listrik memerlukan pengisian daya terlebih dahulu. Kekhawatiran masyarakat soal pengisian daya motor listrik yakni butuh waktu lama untuk mengisinya. \n\nNamun tenang, saat ini teknologi pengisian daya kendaraan listrik sudah berkembang pesat. Saat ini sudah ada fitur fast charging pada kendaraan listrik. Hal ini memungkinkan pengguna bisa mengisi baterai dalam waktu dua jam. \n\nMisalnya saja pada motor listrik uwinfly Ts 3 Pro, motor tersebut bisa mengisi daya 0-80% dalam waktu 6 jam saja. Tenang saja, meski bisa mengisi daya dengan cepat tetapi kondisi charger dan motor tidak akan panas. Karena motor tersebut telah dilengkapi dengan cooling fan sebagai pendingin.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"7. Dapat Dicas di Rumah"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nSalah satu pertanyaan terbesar pengguna adalah apakah motor listrik bisa dicas di rumah? Menurut data dari pln.go.id , motor listrik dapat dicas di rumah. Pengguna bisa mengisi daya sebanyak seminggu dua kali. \n\nJangan khawatir soal tagihan listrik membengkak, karena motor listrik ini cukup hemat. Jarak sekitar 40 km membutuhkan energi listrik sebesar 1 kWh. Bahkan jika Anda mengisi daya di tempat pengisian, Anda hanya perlu mengeluarkan uang 2 ribu rupiah saja. \n\nBiaya ini tentunya jauh lebih murah meriah ketimbang harus memakai kendaraan konvensional. Terlebih lagi harga BBM di Indonesia sudah naik, jadi sudah saatnya kita beralih ke motor listrik.\n"
                          }
                        </React.Fragment>
                      </React.Fragment>
                    ) : (
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"Uwinfly.co.id -"}
                        </span>
                        <React.Fragment>
                          {
                            " Kendaraan listrik saat ini tengah dikembangkan oleh produsen otomotif. Bukan tanpa alasan, pasalnya banyak kegunaan motor listrik dalam kehidupan sehari-hari. \n\nMisalnya saja, motor listrik bisa berguna untuk membuat hidup lebih sehat, ramah lingkungan, hingga mengurangi polusi udara. Dengan berbagai keunggulan ini, motor listrik bisa menjadi solusi kendaraan masa depan. \n\nBagi Anda yang masih awam mungkin akan bertanya-tanya, apa itu motor listrik dan cara kerjanya? Kami akan memberikan informasi mendalam mengenai motor listrik tersebut hingga keunggulannya.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {
                            "Kegunaan Motor Listrik dalam Kehidupan Sehari-hari "
                          }
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nMotor listrik adalah sebuah kendaraan bermotor yang memakai tenaga listrik sebagai energinya. Pada motor listrik menggunakan mesin penggerak semacam dinamo. \n\nSecara umum, ada tiga komponen motor listrik yang sangat penting, yakni baterai sebagai sumber energi, dinamo atau rotor sebagai penggerak, dan V-Belt sebagai penghubung putaran rotor ke roda belakang. \n\nCara kerja motor listrik yakni arus listrik berjalan menuju dinamo dan akan menggerakkan dinamo. Perputaran dinamo ini akan diteruskan ke roda belakang melalui V-Belt. Sehingga motor listrik bisa bergerak dan berjalan sesuai dengan kencang. \n\nLantas apa fungsi motor listrik dalam kehidupan sehari hari? Kegunaan dari sepeda motor listrik yaitu sebagai kendaraan ramah lingkungan. Kendaraan yang satu ini dapat digunakan untuk mempermudah aktivitas. \n\nMisalnya untuk melakukan perjalanan jauh, mengangkut barang, hingga untuk nongkrong dengan teman-teman. Hal yang paling membanggakan yakni semua aktivitas dengan motor tersebut tidak menghasilkan polusi udara. Sehingga kualitas udara bisa tetap terjaga dan tubuh bisa tetap sehat.  \n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"Kontrol sepenuhnya motor listrik melalui ponsel"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nKini motor listrik semakin canggih dengan menyematkan teknologi IoT (Internet of Things) dan terhububung dengan ponsel. Dengan berbagai fitur mutakhir, aplikasi dirancang untuk meningkatkan pengalaman berkendara dan membantu mendapatkan manfaat maksimal dari kendaraan listrik. Salah satu fitur utama aplikasi adalah kemampuan untuk menghidupkan dan mematikan sepeda motor EV (Electric Vehicle) dari jarak jauh, langsung melalui ponsel pribadi pengendara. Hal ini memungkinkan Anda dengan cepat dan mudah menghidupkan kendaraan dan pergi ke jalan, tanpa perlu kunci atau kontak fisik dengan sakelar.\n\nSelain kemampuan start dan stop jarak jauh, aplikasi juga memungkinkan untuk melacak riwayat perjalanan, termasuk jarak yang ditempuh dan waktu yang dihabiskan setelah berkendara. Fitur ini sangat berguna untuk mengawasi kebiasaan berkendara Anda dan memantau kemajuan dari waktu ke waktu.\n\nKini motor listrik semakin canggih dengan menyematkan teknologi IoT (Internet of Things) dan terhububung dengan ponsel. Dengan berbagai fitur mutakhir, aplikasi dirancang untuk meningkatkan pengalaman berkendara dan membantu mendapatkan manfaat maksimal dari kendaraan listrik. Salah satu fitur utama aplikasi adalah kemampuan untuk menghidupkan dan mematikan sepeda motor EV (Electric Vehicle) dari jarak jauh, langsung melalui ponsel pribadi pengendara. Hal ini memungkinkan Anda dengan cepat dan mudah menghidupkan kendaraan dan pergi ke jalan, tanpa perlu kunci atau kontak fisik dengan sakelar.\n\nSelain kemampuan start dan stop jarak jauh, aplikasi juga memungkinkan untuk melacak riwayat perjalanan, termasuk jarak yang ditempuh dan waktu yang dihabiskan setelah berkendara. Fitur ini sangat berguna untuk mengawasi kebiasaan berkendara Anda dan memantau kemajuan dari waktu ke waktu.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {
                            "Kelebihan Motor Listrik Dibandingkan dengan Motor Bensin "
                          }
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"1. Ramah Lingkungan"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nPasti banyak yang penasaran, apakah motor listrik mengeluarkan asap? Nah motor listrik tidak menghasilkan asap sama sekali. Ini artinya, kendaraan tersebut tidak menghasilkan emisi gas buang yang menyebabkan polusi udara.\n\nMengutip dari laman Kemenperin.go.id, pemerintah juga telah menargetkan untuk mencapai net zero emisi di tahun 2060 mendatang. Salah satu jalan yang dilakukan oleh Pemerintah Indonesia yakni dengan memperbanyak produksi kendaraan listrik. Kemudian mewajibkan pemerintah pusat dan daerah memakai kendaraan listrik.\n\nKetika semua lapisan masyarakat telah memakai kendaraan listrik, maka akan tercipta lingkungan yang sehat. Polusi udara menjadi berkurang dan tentunya kondisi lingkungan juga bisa menjadi lebih baik lagi.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"2. Menghemat Energi Fosil"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nBahan bakar minyak merupakan sumber energi penggerak mesin kendaraan bermotor. Sayangnya BBM ini merupakan energi fosil yang tidak bisa diciptakan lagi. Keberadaanya pun bisa habis jika manusia tidak bijak memanfaatkannya. \n\nMotor listrik hadir untuk menjawab tantangan kelangkaan energi minyak. Dengan adanya kendaraan listrik, maka bisa lebih menghemat penggunaan BBM. Karena motor bertenaga listrik tidak memerlukan BBM lagi.\n\nTerlebih lagi, harga BBM saat ini cukup mahal ketimbang harga listrik. Saat Anda memakai motor listrik, maka Anda bisa hemat uang dan membantu menghemat energi BBM.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"3. Lebih Hemat Biaya Perawatan"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nSetiap kendaraan bermotor tentunya perlu perawatan harian atau bulanan. Hal ini sangat berguna agar kondisi motor tetap prima dan bisa digunakan untuk berkendara dengan lancar.\n\nPerawatan dan operasional tersebut meliputi bahan bakar, reparasi rem, pengecekan mesin, dan lain sebagainya. Untungnya saat Anda memakai kendaraan listrik, Anda akan jauh lebih hemat dari biaya-biaya tersebut. \n\nKarena motor listrik hanya perlu perawatan bagian baterai dan kondisi mesin. Hal ini akan membuat Anda lebih hemat dalam perawatan kendaraan listrik yang dimiliki.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"4. Lebih Ringan"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nMungkin Anda pernah bertanya-tanya, apakah motor listrik lebih enteng? Ternyata motor listrik memang jauh lebih ringan ketimbang motor konvensional. Hal ini karena motor listrik memakai kerangka dan mesin yang tidak terlalu berat. \n\nBagian kerangka motor listrik didesain untuk menyesuaikan berat penggunanya. Kemudian untuk mesin memakai dinamo yang tentunya lebih ringan ketimbang mesin motor biasa. Karena beratnya cukup ringan, tentunya bisa memberikan keuntungan tersendiri. \n\nMotor listrik yang ringan ini akan membuat kecepatannya jadi lebih tinggi. Anda bisa memacu kendaraan tersebut dan berakselerasi dengan lebih leluasa. Dengan catatan, kondisi medan yang Anda tempuh tidak naik turun perbukitan.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"5. Tidak Bising"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nKeunggulan motor listrik ketimbang motor konvensional yakni tidak bising. Motor listrik biasanya memiliki suara bising karena perlu pembakaran di mesin. Kemudian hasil pembakaran yang berupa gas akan dibuang melalui knalpot. \n\nHal inilah yang membuat motor konvensional memiliki bunyi yang amat bising. Sementara pada motor listrik, sama sekali tidak ada pembakaran di bagian mesin. Bunyi pada mesin motor listrik bersumber dari putaran dinamo atau rotor. \n\nSehingga motor listrik tidak akan mengeluarkan bunyi bising sama sekali. Hal tersebut akan memberikan kenyamanan berkendara untuk Anda sendiri dan lingkungan di sekitar Anda. Kehidupan bermasyarakat pun jadi lebih rukun serta lebih indah.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"6. Pengisian Daya Lebih Cepat"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nKendaraan dengan energi listrik memerlukan pengisian daya terlebih dahulu. Kekhawatiran masyarakat soal pengisian daya motor listrik yakni butuh waktu lama untuk mengisinya. \n\nNamun tenang, saat ini teknologi pengisian daya kendaraan listrik sudah berkembang pesat. Saat ini sudah ada fitur fast charging pada kendaraan listrik. Hal ini memungkinkan pengguna bisa mengisi baterai dalam waktu dua jam. \n\nMisalnya saja pada motor listrik uwinfly Ts 3 Pro, motor tersebut bisa mengisi daya 0-80% dalam waktu 6 jam saja. Tenang saja, meski bisa mengisi daya dengan cepat tetapi kondisi charger dan motor tidak akan panas. Karena motor tersebut telah dilengkapi dengan cooling fan sebagai pendingin.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"7. Dapat Dicas di Rumah"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {""}
                        </span>
                        <React.Fragment>
                          {
                            "\nSalah satu pertanyaan terbesar pengguna adalah apakah motor listrik bisa dicas di rumah? Menurut data dari pln.go.id , motor listrik dapat dicas di rumah. Pengguna bisa mengisi daya sebanyak seminggu dua kali. \n\nJangan khawatir soal tagihan listrik membengkak, karena motor listrik ini cukup hemat. Jarak sekitar 40 km membutuhkan energi listrik sebesar 1 kWh. Bahkan jika Anda mengisi daya di tempat pengisian, Anda hanya perlu mengeluarkan uang 2 ribu rupiah saja. \n\nBiaya ini tentunya jauh lebih murah meriah ketimbang harus memakai kendaraan konvensional. Terlebih lagi harga BBM di Indonesia sudah naik, jadi sudah saatnya kita beralih ke motor listrik.\n"
                          }
                        </React.Fragment>
                      </React.Fragment>
                    )}
                  </div>
                </section>
              </div>
            </div>
          </section>
          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section className={classNames(projectcss.all, sty.section__qBfub)}>
              <div className={classNames(projectcss.all, sty.columns___0VDqj)}>
                <div className={classNames(projectcss.all, sty.column__nkq2I)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___9QJlC)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? {
                            src: "/plasmic/uwinfly/images/newProject1Png.png",
                            fullWidth: 800,
                            fullHeight: 600,
                            aspectRatio: undefined
                          }
                        : {
                            src: "/plasmic/uwinfly/images/newProjectpng.png",
                            fullWidth: 800,
                            fullHeight: 600,
                            aspectRatio: undefined
                          }
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__xC3Jg)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eolrm
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Feb 20, 2024"
                      : "Feb 15, 2024"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__r5Mh5
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Cara Merawat Motor Listrik: Apa Saja Dilakukan?"
                      : "Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qisC5
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Akhir-akhir ini motor listrik semakin populer sebagai alternatif "
                      : "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"}
                  </div>
                </div>
              </div>
            </section>
          ) : null}
          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section className={classNames(projectcss.all, sty.section__ai9UR)}>
              <div className={classNames(projectcss.all, sty.columns__aXnYy)}>
                <div className={classNames(projectcss.all, sty.column__t9Hqr)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___4OfY7)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? {
                            src: "/plasmic/uwinfly/images/_648F793C6Dcd1Jpeg.jpg",
                            fullWidth: 1200,
                            fullHeight: 800,
                            aspectRatio: undefined
                          }
                        : {
                            src: "/plasmic/uwinfly/images/newProjectpng.png",
                            fullWidth: 800,
                            fullHeight: 600,
                            aspectRatio: undefined
                          }
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__nGKfl)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__c7OwL
                    )}
                  >
                    {"Feb 15, 2024"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zktpF
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "5 Cara Perawatan Motor Listrik, Mudah Banget!"
                      : "Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cv93U
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Perawatan motor listrik wajib diketahui setiap pemilik jika ingin kendaraannya "
                      : "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"}
                  </div>
                </div>
              </div>
            </section>
          ) : null}
          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section
              className={classNames(projectcss.all, sty.section___7JB7S)}
            >
              <div className={classNames(projectcss.all, sty.columns__foIq5)}>
                <div className={classNames(projectcss.all, sty.column__c95ZP)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__g44Qi)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/uwinfly/images/newProjectpng.png",
                      fullWidth: 800,
                      fullHeight: 600,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__napEb)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___51XOf
                    )}
                  >
                    {"Feb 15, 2024"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__q3P2S
                    )}
                  >
                    {"Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__m9X03
                    )}
                  >
                    {
                      "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"
                    }
                  </div>
                </div>
              </div>
            </section>
          ) : null}
          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section className={classNames(projectcss.all, sty.section___0HJf)}>
              <div className={classNames(projectcss.all, sty.columns__yp7J1)}>
                <div className={classNames(projectcss.all, sty.column__weIqa)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__vmMWr)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/uwinfly/images/newProjectpng.png",
                      fullWidth: 800,
                      fullHeight: 600,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__eqieB)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7EyA1
                    )}
                  >
                    {"Feb 15, 2024"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qd7ZY
                    )}
                  >
                    {"Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bJn
                    )}
                  >
                    {
                      "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"
                    }
                  </div>
                </div>
              </div>
            </section>
          ) : null}
          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section className={classNames(projectcss.all, sty.section__iP8VI)}>
              <div className={classNames(projectcss.all, sty.columns___2HWno)}>
                <div className={classNames(projectcss.all, sty.column__vmcIr)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__kgt0Z)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/uwinfly/images/newProjectpng.png",
                      fullWidth: 800,
                      fullHeight: 600,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__d1LbA)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wmWfm
                    )}
                  >
                    {"Feb 15, 2024"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xs1Ze
                    )}
                  >
                    {"Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qlB6L
                    )}
                  >
                    {
                      "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"
                    }
                  </div>
                </div>
              </div>
            </section>
          ) : null}
          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section
              className={classNames(projectcss.all, sty.section___5MnXg)}
            >
              <div className={classNames(projectcss.all, sty.columns__rA4Ml)}>
                <div className={classNames(projectcss.all, sty.column___7MxN7)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__jy3VQ)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/uwinfly/images/newProjectpng.png",
                      fullWidth: 800,
                      fullHeight: 600,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__gg7W1)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pJrzd
                    )}
                  >
                    {"Feb 15, 2024"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ymiae
                    )}
                  >
                    {"Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7R
                    )}
                  >
                    {
                      "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"
                    }
                  </div>
                </div>
              </div>
            </section>
          ) : null}
          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section className={classNames(projectcss.all, sty.section__aUcG)}>
              <div className={classNames(projectcss.all, sty.columns__sJpG)}>
                <div className={classNames(projectcss.all, sty.column__dRey9)}>
                  <section
                    className={classNames(projectcss.all, sty.section__yX9Kv)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__f4Xev)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/uwinfly/images/newProject2Png.png",
                        fullWidth: 800,
                        fullHeight: 600,
                        aspectRatio: undefined
                      }}
                    />
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__wo5X1)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gUtS
                      )}
                    >
                      {"June 24, 2024"}
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__xge4V
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"7 Kelebihan dan Kegunaan Motor Listrik"}
                    </PlasmicLink__>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__agKgf
                      )}
                    >
                      {
                        "Kendaraan listrik saat ini tengah dikembangkan oleh produsen otomotif. "
                      }
                    </div>
                  </section>
                </div>
              </div>
            </section>
          ) : null}
          <FooterMain
            data-plasmic-name={"footerMain"}
            data-plasmic-override={overrides.footerMain}
            className={classNames("__wab_instance", sty.footerMain)}
          />

          <section className={classNames(projectcss.all, sty.section___2ArDe)}>
            <div className={classNames(projectcss.all, sty.columns__e2UCp)}>
              <div className={classNames(projectcss.all, sty.column___2P0Hp)}>
                <div
                  className={classNames(projectcss.all, sty.columns___0A0R6)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column___3Ho09)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__e7V4Y
                      )}
                    >
                      {"Pembayaran :"}
                    </div>
                  </div>
                  <div className={classNames(projectcss.all, sty.column__j85T)}>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__eUwUk)}
                      displayHeight={"80px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/uwinfly/images/_1646110410MandiriVapng.png",
                        fullWidth: 257,
                        fullHeight: 225,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__kso2X)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___4Vujc)}
                      displayHeight={"62px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/uwinfly/images/bcApng.png",
                        fullWidth: 257,
                        fullHeight: 225,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__s4TbJ)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__d19Zs)}
                      displayHeight={"66px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/uwinfly/images/download1Png.png",
                        fullWidth: 257,
                        fullHeight: 225,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__wTePn)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___312Qj)}
                      displayHeight={"80px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/uwinfly/images/downloadpng.png",
                        fullWidth: 225,
                        fullHeight: 225,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </section>
          <PlasmicHead
            data-plasmic-name={"pageMetadataOverride"}
            data-plasmic-override={overrides.pageMetadataOverride}
            className={classNames("__wab_instance", sty.pageMetadataOverride)}
            description={"informasi  sepeda listrik dan motor listrik "}
            image={"/plasmic/uwinfly/images/logopng.png"}
            title={"blog "}
          />

          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section className={classNames(projectcss.all, sty.section__lqzgC)}>
              <div className={classNames(projectcss.all, sty.columns__wiwVc)}>
                <div className={classNames(projectcss.all, sty.column__yEiJd)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__hzHtF)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/uwinfly/images/newProjectpng.png",
                      fullWidth: 800,
                      fullHeight: 600,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__cNa6G)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__icwIs
                    )}
                  >
                    {"Feb 15, 2024"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__skhRj
                    )}
                  >
                    {"Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cvxzZ
                    )}
                  >
                    {
                      "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"
                    }
                  </div>
                </div>
              </div>
            </section>
          ) : null}
          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section className={classNames(projectcss.all, sty.section__me11P)}>
              <div className={classNames(projectcss.all, sty.columns__o4E)}>
                <div className={classNames(projectcss.all, sty.column__lsnKa)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__ejIMf)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/uwinfly/images/newProjectpng.png",
                      fullWidth: 800,
                      fullHeight: 600,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__jfVTf)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wrai3
                    )}
                  >
                    {"Feb 15, 2024"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qiGjt
                    )}
                  >
                    {"Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lOak7
                    )}
                  >
                    {
                      "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"
                    }
                  </div>
                </div>
              </div>
              <section
                className={classNames(projectcss.all, sty.section___9K8Fh)}
              >
                <div className={classNames(projectcss.all, sty.columns__pdqn)}>
                  <div
                    className={classNames(projectcss.all, sty.column__ugmmw)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__wczBq)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/uwinfly/images/newProjectpng.png",
                        fullWidth: 800,
                        fullHeight: 600,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__diakv)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__d4S6I
                      )}
                    >
                      {"Feb 15, 2024"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eto7W
                      )}
                    >
                      {"Baterai Motor Listrik Agar Performa Terjaga"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zJvlS
                      )}
                    >
                      {
                        "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"
                      }
                    </div>
                  </div>
                </div>
              </section>
            </section>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navigationBar",
    "link1",
    "link2",
    "link3",
    "link4",
    "link5",
    "link6",
    "images03",
    "footerMain",
    "pageMetadataOverride"
  ],
  navigationBar: [
    "navigationBar",
    "link1",
    "link2",
    "link3",
    "link4",
    "link5",
    "link6"
  ],
  link1: ["link1"],
  link2: ["link2"],
  link3: ["link3"],
  link4: ["link4"],
  link5: ["link5"],
  link6: ["link6"],
  images03: ["images03"],
  footerMain: ["footerMain"],
  pageMetadataOverride: ["pageMetadataOverride"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navigationBar: typeof NavigationBar;
  link1: typeof Link1;
  link2: typeof Link2;
  link3: typeof Link3;
  link4: typeof Link4;
  link5: typeof Link5;
  link6: typeof Link6;
  images03: typeof PlasmicImg__;
  footerMain: typeof FooterMain;
  pageMetadataOverride: typeof PlasmicHead;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  Plasmic_7KelebihanDanKegunaanMotorListrik__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: Plasmic_7KelebihanDanKegunaanMotorListrik__VariantsArgs;
    args?: Plasmic_7KelebihanDanKegunaanMotorListrik__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit< // Specify variants directly as props
    Plasmic_7KelebihanDanKegunaanMotorListrik__VariantsArgs,
    ReservedPropsType
  > &
    /* Specify args directly as props*/ Omit<
      Plasmic_7KelebihanDanKegunaanMotorListrik__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames:
            Plasmic_7KelebihanDanKegunaanMotorListrik__ArgProps,
          internalVariantPropNames:
            Plasmic_7KelebihanDanKegunaanMotorListrik__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmic_7KelebihanDanKegunaanMotorListrik__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic_7KelebihanDanKegunaanMotorListrik";
  } else {
    func.displayName = `Plasmic_7KelebihanDanKegunaanMotorListrik.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const PageGuard: React.FC<P> = props => (
    <PlasmicPageGuard__
      minRole={null}
      appId={"iWaiTLt8mAup4ReehswsSx"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={true}
    >
      <WrappedComponent {...props} />
    </PlasmicPageGuard__>
  );

  return PageGuard;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "iWaiTLt8mAup4ReehswsSx"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const Plasmic_7KelebihanDanKegunaanMotorListrik = Object.assign(
  // Top-level Plasmic_7KelebihanDanKegunaanMotorListrik renders the root element
  withUsePlasmicAuth(withPlasmicPageGuard(makeNodeComponent("root"))),
  {
    // Helper components rendering sub-elements
    navigationBar: makeNodeComponent("navigationBar"),
    link1: makeNodeComponent("link1"),
    link2: makeNodeComponent("link2"),
    link3: makeNodeComponent("link3"),
    link4: makeNodeComponent("link4"),
    link5: makeNodeComponent("link5"),
    link6: makeNodeComponent("link6"),
    images03: makeNodeComponent("images03"),
    footerMain: makeNodeComponent("footerMain"),
    pageMetadataOverride: makeNodeComponent("pageMetadataOverride"),

    // Metadata about props expected for Plasmic_7KelebihanDanKegunaanMotorListrik
    internalVariantProps:
      Plasmic_7KelebihanDanKegunaanMotorListrik__VariantProps,
    internalArgProps: Plasmic_7KelebihanDanKegunaanMotorListrik__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "7 Kelebihan dan Kegunaan Motor Listrik",
      description:
        "Kendaraan listrik saat ini tengah dikembangkan oleh produsen otomotif. ",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default Plasmic_7KelebihanDanKegunaanMotorListrik;
/* prettier-ignore-end */
