// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iWaiTLt8mAup4ReehswsSx
// Component: kM2OqxWGBH0e

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import Link1 from "../../Link1"; // plasmic-import: Wk3pm7NzsIY9/component
import Link2 from "../../Link2"; // plasmic-import: f0ftlBRhAHPN/component
import Link3 from "../../Link3"; // plasmic-import: P6OuWwiFq4gQ/component
import Link4 from "../../Link4"; // plasmic-import: b5zzKfYNksQk/component
import Link5 from "../../Link5"; // plasmic-import: jy_zqM-l3sYE/component
import Link6 from "../../Link6"; // plasmic-import: qdfwHKfwtv8_/component
import Button from "../../Button"; // plasmic-import: f3lmI1Q2JQuQ/component
import FooterMain from "../../FooterMain"; // plasmic-import: qoZVCK7paFuV/component
import { PlasmicHead } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantssppb0UOhrN5L } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: Sppb0uOhrN5l/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: iWaiTLt8mAup4ReehswsSx/projectcss
import sty from "./PlasmicBateraiMotorListrikAgarPerformaTerjaga.module.css"; // plasmic-import: kM2OqxWGBH0e/css

import ProfileCircleSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__ProfileCircleSvgrepoCom1Svg"; // plasmic-import: 0qa3aoynIlk5/icon
import BestSellersvgIcon from "./icons/PlasmicIcon__BestSellersvg"; // plasmic-import: gEr3vmMDIr_A/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: q0SxIWf05NzX/icon
import MotorcyclesvgIcon from "./icons/PlasmicIcon__Motorcyclesvg"; // plasmic-import: bB21gLC1MPi2/icon
import PinsvgIcon from "./icons/PlasmicIcon__Pinsvg"; // plasmic-import: d5Rc8pnBZxlJ/icon
import ArrowLeftSvgrepoComsvgIcon from "./icons/PlasmicIcon__ArrowLeftSvgrepoComsvg"; // plasmic-import: n23QXdz0xMhj/icon

createPlasmicElementProxy;

export type PlasmicBateraiMotorListrikAgarPerformaTerjaga__VariantMembers = {};
export type PlasmicBateraiMotorListrikAgarPerformaTerjaga__VariantsArgs = {};
type VariantPropType =
  keyof PlasmicBateraiMotorListrikAgarPerformaTerjaga__VariantsArgs;
export const PlasmicBateraiMotorListrikAgarPerformaTerjaga__VariantProps =
  new Array<VariantPropType>();

export type PlasmicBateraiMotorListrikAgarPerformaTerjaga__ArgsType = {};
type ArgPropType =
  keyof PlasmicBateraiMotorListrikAgarPerformaTerjaga__ArgsType;
export const PlasmicBateraiMotorListrikAgarPerformaTerjaga__ArgProps =
  new Array<ArgPropType>();

export type PlasmicBateraiMotorListrikAgarPerformaTerjaga__OverridesType = {
  root?: Flex__<"div">;
  navigationBar?: Flex__<typeof NavigationBar>;
  link1?: Flex__<typeof Link1>;
  link2?: Flex__<typeof Link2>;
  link3?: Flex__<typeof Link3>;
  link4?: Flex__<typeof Link4>;
  link5?: Flex__<typeof Link5>;
  link6?: Flex__<typeof Link6>;
  images02?: Flex__<typeof PlasmicImg__>;
  footerMain?: Flex__<typeof FooterMain>;
  pageMetadataOverride?: Flex__<typeof PlasmicHead>;
};

export interface DefaultBateraiMotorListrikAgarPerformaTerjagaProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBateraiMotorListrikAgarPerformaTerjaga__RenderFunc(props: {
  variants: PlasmicBateraiMotorListrikAgarPerformaTerjaga__VariantsArgs;
  args: PlasmicBateraiMotorListrikAgarPerformaTerjaga__ArgsType;
  overrides: PlasmicBateraiMotorListrikAgarPerformaTerjaga__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantssppb0UOhrN5L()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicBateraiMotorListrikAgarPerformaTerjaga.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={
            PlasmicBateraiMotorListrikAgarPerformaTerjaga.pageMetadata.title
          }
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={
            PlasmicBateraiMotorListrikAgarPerformaTerjaga.pageMetadata.title
          }
        />
        <meta
          key="description"
          name="description"
          content={
            PlasmicBateraiMotorListrikAgarPerformaTerjaga.pageMetadata
              .description
          }
        />
        <meta
          key="og:description"
          property="og:description"
          content={
            PlasmicBateraiMotorListrikAgarPerformaTerjaga.pageMetadata
              .description
          }
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={
            PlasmicBateraiMotorListrikAgarPerformaTerjaga.pageMetadata
              .description
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <section className={classNames(projectcss.all, sty.section__jAgtT)}>
            <NavigationBar
              data-plasmic-name={"navigationBar"}
              data-plasmic-override={overrides.navigationBar}
              brand={
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link___50Xg2
                  )}
                  component={Link}
                  href={`/`}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__wePik)}
                    displayHeight={"100px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: "/plasmic/uwinfly/images/logopng.png",
                      fullWidth: 512,
                      fullHeight: 512,
                      aspectRatio: undefined
                    }}
                  />
                </PlasmicLink__>
              }
              className={classNames("__wab_instance", sty.navigationBar)}
              closeButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__kPbWc)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "20px"
                      : "auto"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "20px"
                      : "auto"
                  }
                  src={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? {
                          src: "/plasmic/uwinfly/images/_3F1C0155019E22Ca2146D6372Fa054D8Svg.svg",
                          fullWidth: 150,
                          fullHeight: 150,
                          aspectRatio: 1
                        }
                      : "https://static1.plasmic.app/close.svg"
                  }
                />
              }
              forceOpenMenu={
                hasVariant(globalVariants, "screen", "mobile") ? false : true
              }
              itemsGap={hasVariant(globalVariants, "screen", "mobile") ? 8 : 8}
              menuItems={
                <React.Fragment>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__c9Bgh
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    <Link1
                      data-plasmic-name={"link1"}
                      data-plasmic-override={overrides.link1}
                      className={classNames("__wab_instance", sty.link1)}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__hpdwY
                    )}
                    component={Link}
                    href={`/about-us`}
                    platform={"nextjs"}
                  >
                    <Link2
                      data-plasmic-name={"link2"}
                      data-plasmic-override={overrides.link2}
                      className={classNames("__wab_instance", sty.link2)}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__udyNa
                    )}
                    component={Link}
                    href={`/Mitra`}
                    platform={"nextjs"}
                  >
                    <Link3
                      data-plasmic-name={"link3"}
                      data-plasmic-override={overrides.link3}
                      className={classNames("__wab_instance", sty.link3)}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__jGPqA
                    )}
                    component={Link}
                    href={`/Blog`}
                    platform={"nextjs"}
                  >
                    <Link4
                      data-plasmic-name={"link4"}
                      data-plasmic-override={overrides.link4}
                      className={classNames("__wab_instance", sty.link4)}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__nToHr
                    )}
                    component={Link}
                    href={`/persyaratan`}
                    platform={"nextjs"}
                  >
                    <Link5
                      data-plasmic-name={"link5"}
                      data-plasmic-override={overrides.link5}
                      className={classNames("__wab_instance", sty.link5)}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__ty6ER
                    )}
                    component={Link}
                    href={`/Kotak-kami`}
                    platform={"nextjs"}
                  >
                    <Link6
                      data-plasmic-name={"link6"}
                      data-plasmic-override={overrides.link6}
                      className={classNames("__wab_instance", sty.link6)}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__ivi5
                    )}
                    component={Link}
                    href={`/Profile`}
                    platform={"nextjs"}
                  >
                    <ProfileCircleSvgrepoCom1SvgIcon
                      className={classNames(projectcss.all, sty.svg__i2Pyc)}
                      role={"img"}
                    />
                  </PlasmicLink__>
                </React.Fragment>
              }
              openButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___93Gdi)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "25px"
                      : "35px"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  src={{
                    src: "/plasmic/uwinfly/images/iconsvg.svg",
                    fullWidth: 231,
                    fullHeight: 150,
                    aspectRatio: 1.537966
                  }}
                />
              }
              responsiveBreakpoint={768}
            />

            <section className={classNames(projectcss.all, sty.section__gMeo)}>
              <div className={classNames(projectcss.all, sty.columns__ovApO)}>
                <div
                  className={classNames(projectcss.all, sty.column___3XtQw)}
                />

                <div
                  className={classNames(projectcss.all, sty.column__fzsze)}
                />
              </div>
            </section>
          </section>
          <section className={classNames(projectcss.all, sty.section__y38AT)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__wjl)}
            >
              <div className={classNames(projectcss.all, sty.column__qdrO4)}>
                <Button
                  className={classNames("__wab_instance", sty.button__xfb6S)}
                  showStartIcon={true}
                  startIcon={
                    <BestSellersvgIcon
                      className={classNames(projectcss.all, sty.svg__ycHv)}
                      role={"img"}
                    />
                  }
                >
                  {"Best seller"}
                </Button>
              </div>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.column__sGc9E
                )}
                component={Link}
                href={`/Produk`}
                platform={"nextjs"}
              >
                <Button
                  className={classNames("__wab_instance", sty.button__frUz)}
                  showStartIcon={true}
                  startIcon={
                    <MotorcyclesvgIcon
                      className={classNames(projectcss.all, sty.svg___7V3Gn)}
                      role={"img"}
                    />
                  }
                >
                  {"Produk"}
                </Button>
              </PlasmicLink__>
              <div className={classNames(projectcss.all, sty.column__biTVe)}>
                <Button
                  className={classNames("__wab_instance", sty.button__uJfmq)}
                  showStartIcon={true}
                  startIcon={
                    <PinsvgIcon
                      className={classNames(projectcss.all, sty.svg__zaNmD)}
                      role={"img"}
                    />
                  }
                >
                  {"Lokasi"}
                </Button>
              </div>
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section___4KYna)}>
            <div className={classNames(projectcss.all, sty.columns___4POt)}>
              <div className={classNames(projectcss.all, sty.column__iKt2Q)}>
                <Button
                  className={classNames("__wab_instance", sty.button__fS8RP)}
                  showStartIcon={true}
                >
                  {"Best seller"}
                </Button>
              </div>
              <div className={classNames(projectcss.all, sty.column__sRoiX)}>
                <Button
                  className={classNames("__wab_instance", sty.button___9UlXb)}
                  showStartIcon={true}
                  startIcon={
                    <BestSellersvgIcon
                      className={classNames(projectcss.all, sty.svg__bh51B)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3Ebpw
                    )}
                  >
                    {"Best seller"}
                  </div>
                </Button>
              </div>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.column__snQkH
                )}
                component={Link}
                href={`/Produk`}
                platform={"nextjs"}
              >
                <Button
                  className={classNames("__wab_instance", sty.button__mJaC3)}
                  showStartIcon={true}
                  startIcon={
                    <MotorcyclesvgIcon
                      className={classNames(projectcss.all, sty.svg__n57Nq)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eqHtf
                    )}
                  >
                    {"Produk"}
                  </div>
                </Button>
              </PlasmicLink__>
              <div className={classNames(projectcss.all, sty.column__fHYjM)}>
                <Button
                  className={classNames("__wab_instance", sty.button__wVqy5)}
                  showStartIcon={true}
                  startIcon={
                    <PinsvgIcon
                      className={classNames(projectcss.all, sty.svg__brJ)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lOf1F
                    )}
                  >
                    {"Lokasi"}
                  </div>
                </Button>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section___1YV9H)}>
            <div className={classNames(projectcss.all, sty.columns__f4Fkv)}>
              <div className={classNames(projectcss.all, sty.column__eK7O)}>
                <section
                  className={classNames(projectcss.all, sty.section__ml5C)}
                >
                  <div
                    className={classNames(projectcss.all, sty.columns__mv4S6)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__fBiVr)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__qRas
                        )}
                        component={Link}
                        href={`/Blog`}
                        platform={"nextjs"}
                      >
                        <ArrowLeftSvgrepoComsvgIcon
                          className={classNames(projectcss.all, sty.svg__bc5L0)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__btLdP)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__k6F6
                        )}
                      >
                        {"Feb 15, 2024"}
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fdDzt
                    )}
                  >
                    {"Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kaf8J
                    )}
                  >
                    {
                      "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"
                    }
                  </div>
                </section>
                <section
                  className={classNames(projectcss.all, sty.section___9LwHk)}
                >
                  <PlasmicImg__
                    data-plasmic-name={"images02"}
                    data-plasmic-override={overrides.images02}
                    alt={"Baterai Motor Listrik Agar Performa Terjaga"}
                    className={classNames(sty.images02)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/uwinfly/images/newProjectpng.png",
                      fullWidth: 800,
                      fullHeight: 600,
                      aspectRatio: undefined
                    }}
                  />
                </section>
                <section
                  className={classNames(projectcss.all, sty.section__rlRny)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dhqTb
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Uwinfly.co.id"}
                      </span>
                      <React.Fragment>
                        {
                          " Pemilik sepeda motor listrik perlu mengetahui bagaimana cara merawat baterai yang ada pada kendaraan. Pasalnya, cara merawat baterai motor listrik yang benar bisa memperpanjang usia pakai dari kendaraan.\nUntuk menjaga dan merawat agar motor listrik Anda tetap prima, ada beberapa tips supaya performa baterai tetap baik dalam pemakaian sehari-hari. Berikut cara merawat baterai motor listrik.\n\n"
                        }
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"1. Hindari mengisi ulang baterai di bawah 20 persen"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {""}
                      </span>
                      <React.Fragment>
                        {
                          "\nSebaiknya Anda menghindari mengisi ulang daya baterai dalam kondisi yang sangat rendah dengan indikator di bawah 20 persen. Hal ini dapat merusak komponen dan dapat mengacaukan kinerja baterai. \n\nAnda disarankan untuk mengisi ulang daya ketika kondisi baterai dalam posisi 25 persen sampai dengan 80 persen. Kondisi ini dapat merawat performa baterai tetap prima.\n\n"
                        }
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"2. Mengisi baterai secara berkala"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {""}
                      </span>
                      <React.Fragment>
                        {
                          "\nAnda juga perlu mengisi baterai motor listrik secara berkala. Meski jarang digunakan, tapi baterai tetap harus diisi ulang setidaknya setiap dua atau tiga hari sekali agar performa tetap terjaga.\n\n"
                        }
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"3. Hindari mengisi daya ketika kondisi baterai panas"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {""}
                      </span>
                      <React.Fragment>
                        {
                          "\nKondisi panas yang berlebihan dapat merusak komponen di dalam baterai. Oleh karena itu, disarankan untuk menunggunya beberapa saat agar kondisi temperatur turun dan tidak panas.\n\n"
                        }
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"4. Parkir kendaraan di tempat yang sejuk"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {""}
                      </span>
                      <React.Fragment>
                        {
                          "\nPemilik motor listrik juga tidak disarankan untuk parkir di luar ruangan yang terkena sinar matahari langsung. Sinar matahari membuat panas pada baterai lithium dan hal ini dapat merusak masa guna pakai baterai menjadi tidak bertahan lama.\n\nOleh sebab itu, ada baiknya parkir motor listrik Anda di lokasi yang teduh dan tidak terkena sinar matahari langsung. Selain itu, panas matahari juga dapat mengakibatkan panas pada penghantar panas lithium, sehingga lama kelamaan kinerja penghantar panas menurun dan akan mengakibatkan kerusakan.\n\n"
                        }
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {
                          "5. Hindari gunakan charger dan kabel yang tidak orisinal"
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {""}
                      </span>
                      <React.Fragment>
                        {
                          "\nAnda juga tidak disarankan menggunakan charger dan kabel yang tidak orisinal, karena dapat membuat banyak proses pemanasan dalam waktu singkat, sehingga komponen dapat mengakibatkan kerusakan.\n\nGunakan selalu charger dan kabel bawaan atau beli komponen orisinal agar baterai motor listrik Anda tetap terjaga.\n\n"
                        }
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"6. Jangan mengisi baterai terlalu lama"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {""}
                      </span>
                      <React.Fragment>
                        {
                          "\nMengisi daya dalam kondisi terlalu penuh atau terlalu lama setiap saat ternyata tidak diperkenankan, karena hal ini membuat kerja lithium menjadi tidak optimal yaitu banyaknya daya yang masuk berlebihan padahal daya di dalamnya sudah terindikasi cukup. Disarankan mengisi daya dicukupkan ketika indikator mendekati 90-95 persen.\n\n"
                        }
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {
                          "7. Jangan langsung mengisi daya ketika motor baru berhenti"
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {""}
                      </span>
                      <React.Fragment>
                        {
                          "\nAnda harus menunggu kondisi motor mendingin setidaknya 30 menit, maka Anda bisa mengisi ulang baterai motor listrik.\n\n"
                        }
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"8. Hindari membenturkan atau memukul baterai"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {""}
                      </span>
                      <React.Fragment>
                        {
                          "\nKomponen yang menempel pada permukaan akan terguncang dang khawatir akan lepas jika Anda sering memukul baterai lithium. Selain itu, performa komponen baterai juga akan menurun dan mengakibatkan kerusakan atau kebakaran jika sering memukul atau mengetuknya, mengutip Uwinfly."
                        }
                      </React.Fragment>
                    </React.Fragment>
                  </div>
                </section>
              </div>
            </div>
          </section>
          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section
              className={classNames(projectcss.all, sty.section___7Zzcm)}
            >
              <div className={classNames(projectcss.all, sty.columns__lKxY0)}>
                <div className={classNames(projectcss.all, sty.column__v05N8)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__kO498)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? {
                            src: "/plasmic/uwinfly/images/newProject1Png.png",
                            fullWidth: 800,
                            fullHeight: 600,
                            aspectRatio: undefined
                          }
                        : {
                            src: "/plasmic/uwinfly/images/newProjectpng.png",
                            fullWidth: 800,
                            fullHeight: 600,
                            aspectRatio: undefined
                          }
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__snkXd)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__g5Ek9
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Feb 20, 2024"
                      : "Feb 15, 2024"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dWmYx
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Cara Merawat Motor Listrik: Apa Saja Dilakukan?"
                      : "Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mQVd
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Akhir-akhir ini motor listrik semakin populer sebagai alternatif "
                      : "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"}
                  </div>
                </div>
              </div>
            </section>
          ) : null}
          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section className={classNames(projectcss.all, sty.section__dj7Zk)}>
              <div className={classNames(projectcss.all, sty.columns__baDo)}>
                <div className={classNames(projectcss.all, sty.column__qM6Il)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___5F8Dw)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? {
                            src: "/plasmic/uwinfly/images/_648F793C6Dcd1Jpeg.jpg",
                            fullWidth: 1200,
                            fullHeight: 800,
                            aspectRatio: undefined
                          }
                        : {
                            src: "/plasmic/uwinfly/images/newProjectpng.png",
                            fullWidth: 800,
                            fullHeight: 600,
                            aspectRatio: undefined
                          }
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__cbSxx)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wl6LS
                    )}
                  >
                    {"Feb 15, 2024"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sKeBc
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "5 Cara Perawatan Motor Listrik, Mudah Banget!"
                      : "Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ujcmr
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Perawatan motor listrik wajib diketahui setiap pemilik jika ingin kendaraannya "
                      : "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"}
                  </div>
                </div>
              </div>
            </section>
          ) : null}
          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section
              className={classNames(projectcss.all, sty.section___0SXea)}
            >
              <div className={classNames(projectcss.all, sty.columns__ue0S3)}>
                <div className={classNames(projectcss.all, sty.column__s0Ifv)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__lbhIx)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/uwinfly/images/newProjectpng.png",
                      fullWidth: 800,
                      fullHeight: 600,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__nssi7)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aqbyy
                    )}
                  >
                    {"Feb 15, 2024"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dJe6W
                    )}
                  >
                    {"Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aDo8P
                    )}
                  >
                    {
                      "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"
                    }
                  </div>
                </div>
              </div>
            </section>
          ) : null}
          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section
              className={classNames(projectcss.all, sty.section___4OvYh)}
            >
              <div className={classNames(projectcss.all, sty.columns__zwh7O)}>
                <div className={classNames(projectcss.all, sty.column__pBwZf)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__dbqIz)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/uwinfly/images/newProjectpng.png",
                      fullWidth: 800,
                      fullHeight: 600,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__yclrW)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eqneF
                    )}
                  >
                    {"Feb 15, 2024"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uMHds
                    )}
                  >
                    {"Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eLroC
                    )}
                  >
                    {
                      "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"
                    }
                  </div>
                </div>
              </div>
            </section>
          ) : null}
          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section className={classNames(projectcss.all, sty.section__yeRx8)}>
              <div className={classNames(projectcss.all, sty.columns__nHte0)}>
                <div className={classNames(projectcss.all, sty.column__mxuJf)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___9XfvM)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/uwinfly/images/newProjectpng.png",
                      fullWidth: 800,
                      fullHeight: 600,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__epYy8)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rLi2C
                    )}
                  >
                    {"Feb 15, 2024"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__doMp1
                    )}
                  >
                    {"Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__i7QkQ
                    )}
                  >
                    {
                      "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"
                    }
                  </div>
                </div>
              </div>
            </section>
          ) : null}
          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section className={classNames(projectcss.all, sty.section__vYsl)}>
              <div className={classNames(projectcss.all, sty.columns__tsyYu)}>
                <div className={classNames(projectcss.all, sty.column__qvj8P)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__z8RXf)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/uwinfly/images/newProjectpng.png",
                      fullWidth: 800,
                      fullHeight: 600,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__l1R6D)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cqq7
                    )}
                  >
                    {"Feb 15, 2024"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tiR39
                    )}
                  >
                    {"Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iWUt
                    )}
                  >
                    {
                      "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"
                    }
                  </div>
                </div>
              </div>
            </section>
          ) : null}
          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section className={classNames(projectcss.all, sty.section__u6S5O)}>
              <div className={classNames(projectcss.all, sty.columns__kbmyw)}>
                <div className={classNames(projectcss.all, sty.column__qSWkD)}>
                  <section
                    className={classNames(projectcss.all, sty.section___0RoT0)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___7NUkD)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/uwinfly/images/newProject2Png.png",
                        fullWidth: 800,
                        fullHeight: 600,
                        aspectRatio: undefined
                      }}
                    />
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__w5U61)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eMzsZ
                      )}
                    >
                      {"June 24, 2024"}
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__jg5DF
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"7 Kelebihan dan Kegunaan Motor Listrik"}
                    </PlasmicLink__>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bdlH3
                      )}
                    >
                      {
                        "Kendaraan listrik saat ini tengah dikembangkan oleh produsen otomotif. "
                      }
                    </div>
                  </section>
                </div>
              </div>
            </section>
          ) : null}
          <FooterMain
            data-plasmic-name={"footerMain"}
            data-plasmic-override={overrides.footerMain}
            className={classNames("__wab_instance", sty.footerMain)}
          />

          <section className={classNames(projectcss.all, sty.section__cXchM)}>
            <div className={classNames(projectcss.all, sty.columns__aDl1S)}>
              <div className={classNames(projectcss.all, sty.column__hjb2I)}>
                <div className={classNames(projectcss.all, sty.columns__wPQq)}>
                  <div className={classNames(projectcss.all, sty.column__iiR9)}>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kDPc
                      )}
                    >
                      {"Pembayaran :"}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column___5Qsog)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__crxVe)}
                      displayHeight={"80px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/uwinfly/images/_1646110410MandiriVapng.png",
                        fullWidth: 257,
                        fullHeight: 225,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__vMcEx)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__yPoAa)}
                      displayHeight={"62px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/uwinfly/images/bcApng.png",
                        fullWidth: 257,
                        fullHeight: 225,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__pt8Fj)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___89AzO)}
                      displayHeight={"66px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/uwinfly/images/download1Png.png",
                        fullWidth: 257,
                        fullHeight: 225,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div className={classNames(projectcss.all, sty.column__ceAp)}>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__fVfLc)}
                      displayHeight={"80px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/uwinfly/images/downloadpng.png",
                        fullWidth: 225,
                        fullHeight: 225,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </section>
          <PlasmicHead
            data-plasmic-name={"pageMetadataOverride"}
            data-plasmic-override={overrides.pageMetadataOverride}
            className={classNames("__wab_instance", sty.pageMetadataOverride)}
            description={"informasi  sepeda listrik dan motor listrik "}
            image={"/plasmic/uwinfly/images/logopng.png"}
            title={"blog "}
          />

          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section className={classNames(projectcss.all, sty.section__nhpzO)}>
              <div className={classNames(projectcss.all, sty.columns___5Wlfe)}>
                <div className={classNames(projectcss.all, sty.column__ajaGb)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__hBQn4)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/uwinfly/images/newProjectpng.png",
                      fullWidth: 800,
                      fullHeight: 600,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__ja45B)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qVqvT
                    )}
                  >
                    {"Feb 15, 2024"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dIqKf
                    )}
                  >
                    {"Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__imcyb
                    )}
                  >
                    {
                      "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"
                    }
                  </div>
                </div>
              </div>
            </section>
          ) : null}
          {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
            <section className={classNames(projectcss.all, sty.section__cmp5B)}>
              <div className={classNames(projectcss.all, sty.columns__h7Vtd)}>
                <div className={classNames(projectcss.all, sty.column__atins)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__spCk4)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/uwinfly/images/newProjectpng.png",
                      fullWidth: 800,
                      fullHeight: 600,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column___9U1Lg)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3JamB
                    )}
                  >
                    {"Feb 15, 2024"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bagT
                    )}
                  >
                    {"Baterai Motor Listrik Agar Performa Terjaga"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yVzWk
                    )}
                  >
                    {
                      "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"
                    }
                  </div>
                </div>
              </div>
              <section
                className={classNames(projectcss.all, sty.section__yXsQ)}
              >
                <div className={classNames(projectcss.all, sty.columns__xbE8E)}>
                  <div
                    className={classNames(projectcss.all, sty.column__bWu4Z)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__vcAoU)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/uwinfly/images/newProjectpng.png",
                        fullWidth: 800,
                        fullHeight: 600,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__lGipK)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xFzDd
                      )}
                    >
                      {"Feb 15, 2024"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vtvDh
                      )}
                    >
                      {"Baterai Motor Listrik Agar Performa Terjaga"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yWBuj
                      )}
                    >
                      {
                        "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai"
                      }
                    </div>
                  </div>
                </div>
              </section>
            </section>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navigationBar",
    "link1",
    "link2",
    "link3",
    "link4",
    "link5",
    "link6",
    "images02",
    "footerMain",
    "pageMetadataOverride"
  ],
  navigationBar: [
    "navigationBar",
    "link1",
    "link2",
    "link3",
    "link4",
    "link5",
    "link6"
  ],
  link1: ["link1"],
  link2: ["link2"],
  link3: ["link3"],
  link4: ["link4"],
  link5: ["link5"],
  link6: ["link6"],
  images02: ["images02"],
  footerMain: ["footerMain"],
  pageMetadataOverride: ["pageMetadataOverride"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navigationBar: typeof NavigationBar;
  link1: typeof Link1;
  link2: typeof Link2;
  link3: typeof Link3;
  link4: typeof Link4;
  link5: typeof Link5;
  link6: typeof Link6;
  images02: typeof PlasmicImg__;
  footerMain: typeof FooterMain;
  pageMetadataOverride: typeof PlasmicHead;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBateraiMotorListrikAgarPerformaTerjaga__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBateraiMotorListrikAgarPerformaTerjaga__VariantsArgs;
    args?: PlasmicBateraiMotorListrikAgarPerformaTerjaga__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit< // Specify variants directly as props
    PlasmicBateraiMotorListrikAgarPerformaTerjaga__VariantsArgs,
    ReservedPropsType
  > &
    /* Specify args directly as props*/ Omit<
      PlasmicBateraiMotorListrikAgarPerformaTerjaga__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames:
            PlasmicBateraiMotorListrikAgarPerformaTerjaga__ArgProps,
          internalVariantPropNames:
            PlasmicBateraiMotorListrikAgarPerformaTerjaga__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBateraiMotorListrikAgarPerformaTerjaga__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBateraiMotorListrikAgarPerformaTerjaga";
  } else {
    func.displayName = `PlasmicBateraiMotorListrikAgarPerformaTerjaga.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const PageGuard: React.FC<P> = props => (
    <PlasmicPageGuard__
      minRole={null}
      appId={"iWaiTLt8mAup4ReehswsSx"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={true}
    >
      <WrappedComponent {...props} />
    </PlasmicPageGuard__>
  );

  return PageGuard;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "iWaiTLt8mAup4ReehswsSx"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicBateraiMotorListrikAgarPerformaTerjaga = Object.assign(
  // Top-level PlasmicBateraiMotorListrikAgarPerformaTerjaga renders the root element
  withUsePlasmicAuth(withPlasmicPageGuard(makeNodeComponent("root"))),
  {
    // Helper components rendering sub-elements
    navigationBar: makeNodeComponent("navigationBar"),
    link1: makeNodeComponent("link1"),
    link2: makeNodeComponent("link2"),
    link3: makeNodeComponent("link3"),
    link4: makeNodeComponent("link4"),
    link5: makeNodeComponent("link5"),
    link6: makeNodeComponent("link6"),
    images02: makeNodeComponent("images02"),
    footerMain: makeNodeComponent("footerMain"),
    pageMetadataOverride: makeNodeComponent("pageMetadataOverride"),

    // Metadata about props expected for PlasmicBateraiMotorListrikAgarPerformaTerjaga
    internalVariantProps:
      PlasmicBateraiMotorListrikAgarPerformaTerjaga__VariantProps,
    internalArgProps: PlasmicBateraiMotorListrikAgarPerformaTerjaga__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Baterai Motor Listrik Agar Performa Terjaga",
      description:
        "Pemilik sepeda motor listrik perlu mengetahui cara merawat baterai",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicBateraiMotorListrikAgarPerformaTerjaga;
/* prettier-ignore-end */
